name: Run SSH command
on:
  push:
    branches:
      - staging
  pull_request_target:
    types:
      - closed
    branches:
      - staging
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run SSH command
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /root/apk-reproduce/Deku-Android && make release-cd
