name: Run SSH command

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Extract branch name
        id: extract-branch
        run: echo "::set-output name=branch::$(echo $GITHUB_REF | awk -F/ '{print $3}')"

      - name: Run SSH command
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            if [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.pull_request.merged }}" == true && "${{ steps.extract-branch.outputs.branch }}" == "staging" ]]; then
              cd /root/apk-reproduce/Deku-SMS-Android && \
              git checkout ${{ steps.extract-branch.outputs.branch }} && \
              git pull origin ${{ steps.extract-branch.outputs.branch }} && \
              make release-cd
            else
              echo "PR is not merged into 'your_target_branch'. Workflow will not run."
              exit 1
            fi
