name: Run SSH command

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run SSH command
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            if [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.pull_request.merged }}" == true && "${{ github.event.pull_request.base.ref }}" == "staging" ]]; then
              cd /root/apk-reproduce/Deku-SMS-Android && \
              git checkout ${{ github.event.pull_request.base.ref }} && \
              git pull origin ${{ github.event.pull_request.base.ref }} && \
              make release-cd
            else
              echo "PR is not merged into '${{ github.event.pull_request.base.ref }}'. Workflow will not run."
              exit 1
            fi
